name: Capsule_crm
slug: capsule_crm
access: public

description: "Pull customer information from Capsule and see it as a comment on the ticket with a link to the Capsule page.
The app can also update the customer information in Capsule whenever there is a new ticket."

category: crm

tags: 
- crm
- capsule

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: gagan-bopanna
