name: Tactile_crm
slug: tactile_crm
access: public

description: "Pull customer information from Tactile and see it as a comment on the ticket with a link to the Tactile page.
The app can also update the customer information in Tactile whenever there is a new ticket."

category: crm

tags: 
- crm
- tactile

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna

